jaeger_enabled: true
jaeger_namespace: "{{ namespace_prefix }}jaeger"
jaeger_container_registry: "docker.io"
jaeger_image: "jaegertracing/jaeger-query"
jaeger_version: "1.76.0"
jaeger_replicas: 1
jaeger_cpu_requests: "512m"
jaeger_memory_requests: "512Mi"
jaeger_cpu_limits: "1"
jaeger_memory_limits: "1G"
