import typing

class BasicBlocking:
    def health(self, /) -> bool: ...
    def identify(self, /) -> str: ...

class BulkReactionResponse:
    @property
    def created(self, /) -> typing.Any: ...
    @property
    def errors(self, /) -> typing.Any: ...

class ClientSettings:
    def __new__(cls, /, invalid_certs: bool = False, invalid_hostnames: bool = False, certificate_authorities: list[Path] = ..., timeout: int = ...) -> None: ...
    @property
    def certificate_authorities(self, /) -> typing.Any: ...
    @property
    def invalid_certs(self, /) -> bool: ...
    @property
    def invalid_hostnames(self, /) -> bool: ...
    @property
    def timeout(self, /) -> int: ...

class CommitishKinds: ...
class GenericJob: ...

class GenericJobArgs:
    def __new__(cls, /, positionals: list[str] = ..., kwargs: dict[str, list[str]] = ..., switches: list[str] = ..., opts: GenericJobOpts = ...) -> GenericJobArgs: ...
    @property
    def kwargs(self, /) -> typing.Any: ...
    @property
    def opts(self, /) -> GenericJobOpts: ...
    @property
    def positionals(self, /) -> typing.Any: ...
    @property
    def switches(self, /) -> typing.Any: ...

class GenericJobOpts:
    def __new__(cls, /, override_positionals: bool = False, override_kwargs: bool = False, override_cmd: list[str] | None = None) -> GenericJobOpts: ...
    @property
    def override_cmd(self, /) -> typing.Any: ...
    @property
    def override_kwargs(self, /) -> bool: ...
    @property
    def override_positionals(self, /) -> bool: ...

class HandleJobResponse: ...
class JobHandleStatus: ...

class JobsBlocking:
    def checkpoint(self, /, job: GenericJob, checkpoint: str) -> HandleJobResponse: ...
    def sleep(self, /, job_id: UUID, checkpoint: str) -> HandleJobResponse: ...

class Reaction:
    @property
    def args(self, /) -> typing.Any: ...
    @property
    def completed_sub_reactions(self, /) -> int: ...
    @property
    def creator(self, /) -> str: ...
    @property
    def current_stage(self, /) -> int: ...
    @property
    def current_stage_length(self, /) -> int: ...
    @property
    def current_stage_progress(self, /) -> int: ...
    @property
    def ephemeral(self, /) -> typing.Any: ...
    @property
    def generators(self, /) -> typing.Any: ...
    @property
    def group(self, /) -> str: ...
    @property
    def has_cache(self, /) -> bool: ...
    @property
    def id(self, /) -> typing.Any: ...
    @property
    def jobs(self, /) -> typing.Any: ...
    @property
    def parent(self, /) -> typing.Any: ...
    @property
    def parent_ephemeral(self, /) -> typing.Any: ...
    @property
    def pipeline(self, /) -> str: ...
    @property
    def repos(self, /) -> typing.Any: ...
    @property
    def samples(self, /) -> typing.Any: ...
    @property
    def sla(self, /) -> typing.Any: ...
    @property
    def status(self, /) -> ReactionStatus: ...
    @property
    def sub_reactions(self, /) -> int: ...
    @property
    def tags(self, /) -> typing.Any: ...
    @property
    def trigger_depth(self, /) -> typing.Any: ...

class ReactionCache:
    def __new__(cls, /, generic: dict[str, str] = ..., files: list[str] = ...) -> ReactionCache: ...

class ReactionCreation:
    @property
    def id(self, /) -> typing.Any: ...

class ReactionRequest:
    def __new__(cls, /, group: str, pipeline: str, args: dict[str, GenericJobArgs] = ..., sla: int | None = None, tags: list[str] = ..., parent: UUID | None = None, samples: list[str] = ..., buffers: dict[str, str] = ..., repos: list[RepoDependencyRequest] = ..., trigger_depth: int | None = None, cache: ReactionCache = ...) -> ReactionRequest: ...

class ReactionStatus: ...

class ReactionsBlocking:
    def create(self, /, data: ReactionRequest) -> ReactionCreation: ...
    def create_bulk(self, /, reqs: list[ReactionRequest]) -> BulkReactionResponse: ...
    def get(self, /, group: str, id: typing.Any) -> Reaction: ...

class RepoDependency:
    @property
    def commitish(self, /) -> typing.Any: ...
    @commitish.setter
    def commitish(self, /, value: typing.Any) -> None: ...
    @property
    def kind(self, /) -> typing.Any: ...
    @kind.setter
    def kind(self, /, value: typing.Any) -> None: ...
    @property
    def url(self, /) -> str: ...
    @url.setter
    def url(self, /, value: str) -> None: ...

class RepoDependencyRequest:
    def __new__(cls, /, url: str, commitish: str | None = None, kind: CommitishKinds | None = None) -> RepoDependencyRequest: ...

class ThoriumBlocking:
    def __new__(cls, /, host: str, token: str | None = None, username: str | None = None, password: str | None = None, settings: ClientSettings = ...) -> ThoriumBlocking: ...
    @property
    def basic(self, /) -> BasicBlocking: ...
    @property
    def jobs(self, /) -> JobsBlocking: ...
    @property
    def reactions(self, /) -> ReactionsBlocking: ...


from pathlib import Path
from uuid import UUID
