from _typeshed import Incomplete
from collections.abc import Sequence
from datetime import datetime
from ipaddress import IPv4Address, IPv6Address
from os import PathLike
from pathlib import Path
from typing import Any, Final, final

@final
class BasicBlocking:
    def health(self, /) -> bool: ...
    def identify(self, /) -> str: ...

@final
class BulkReactionResponse:
    @property
    def created(self, /) -> list[Incomplete]: ...
    @property
    def errors(self, /) -> dict[int, str]: ...

class CarvedOrigin:
    @final
    class Pcap(CarvedOrigin):
        __match_args__: Final = ("src_ip", "dest_ip", "src_port", "dest_port", "proto", "url")
        def __new__(cls, /, src_ip: IPv4Address |IPv6Address |None, dest_ip: IPv4Address |IPv6Address |None, src_port: int |None, dest_port: int |None, proto: Any |None, url: str |None) -> CarvedOrigin.Pcap: ...
        @property
        def dest_ip(self, /) -> IPv4Address |IPv6Address |None: ...
        @property
        def dest_port(self, /) -> int |None: ...
        @property
        def proto(self, /) -> Any |None: ...
        @property
        def src_ip(self, /) -> IPv4Address |IPv6Address |None: ...
        @property
        def src_port(self, /) -> int |None: ...
        @property
        def url(self, /) -> str |None: ...
    @final
    class Unknown(CarvedOrigin):
        __match_args__: Final = ()
        def __getitem__(self, /, key: int) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> CarvedOrigin.Unknown: ...

@final
class ClientSettings:
    def __new__(cls, /, invalid_certs: bool = False, invalid_hostnames: bool = False, certificate_authorities: Sequence[str |PathLike] = ..., timeout: int = ...) -> ClientSettings: ...
    @property
    def certificate_authorities(self, /) -> list[Path]: ...
    @property
    def invalid_certs(self, /) -> bool: ...
    @property
    def invalid_hostnames(self, /) -> bool: ...
    @property
    def timeout(self, /) -> int: ...

@final
class Comment:
    @property
    def attachments(self, /) -> dict[str, Incomplete]: ...
    @property
    def author(self, /) -> str: ...
    @property
    def comment(self, /) -> str: ...
    @property
    def groups(self, /) -> list[str]: ...
    @property
    def id(self, /) -> Incomplete: ...
    @property
    def uploaded(self, /) -> datetime: ...

@final
class CommitishKinds:
    Branch: Final[CommitishKinds]
    Commit: Final[CommitishKinds]
    Tag: Final[CommitishKinds]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class FileListOpts:
    def __new__(cls, /, cursor: "UUID | None" = None, start: datetime |None = None, end: datetime |None = None, page_size: int = 50, limit: int |None = None, groups: Sequence[str] = ..., tags: dict[str, Sequence[str]] = ..., tags_case_insensitive: bool = False) -> FileListOpts: ...

@final
class FilesBlocking:
    def count(self, /, opts: FileListOpts) -> TagCountsCursor: ...
    def list(self, /, opts: FileListOpts) -> SampleListLineCursor: ...
    def list_details(self, /, opts: FileListOpts) -> SampleCursor: ...

@final
class GenericJob: ...

@final
class GenericJobArgs:
    def __new__(cls, /, positionals: Sequence[str] = ..., kwargs: dict[str, Sequence[str]] = ..., switches: Sequence[str] = ..., opts: GenericJobOpts = ...) -> GenericJobArgs: ...
    @property
    def kwargs(self, /) -> dict[str, list[str]]: ...
    @property
    def opts(self, /) -> GenericJobOpts: ...
    @property
    def positionals(self, /) -> list[str]: ...
    @property
    def switches(self, /) -> list[str]: ...

@final
class GenericJobOpts:
    def __new__(cls, /, override_positionals: bool = False, override_kwargs: bool = False, override_cmd: Sequence[str] |None = None) -> GenericJobOpts: ...
    @property
    def override_cmd(self, /) -> list[str] |None: ...
    @property
    def override_kwargs(self, /) -> bool: ...
    @property
    def override_positionals(self, /) -> bool: ...

@final
class HandleJobResponse: ...

@final
class JobHandleStatus:
    Checkpointed: Final[JobHandleStatus]
    Completed: Final[JobHandleStatus]
    Errored: Final[JobHandleStatus]
    Proceeding: Final[JobHandleStatus]
    Sleeping: Final[JobHandleStatus]
    Waiting: Final[JobHandleStatus]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class JobsBlocking:
    def checkpoint(self, /, job: GenericJob, checkpoint: str) -> HandleJobResponse: ...
    def sleep(self, /, job_id: "UUID", checkpoint: "str") -> "HandleJobResponse": ...

class Origin:
    @final
    class Carved(Origin):
        __match_args__: Final = ("parent", "tool", "dangling", "carved_origin")
        def __new__(cls, /, parent: str, tool: str |None, dangling: bool, carved_origin: CarvedOrigin) -> Origin.Carved: ...
        @property
        def carved_origin(self, /) -> CarvedOrigin: ...
        @property
        def dangling(self, /) -> bool: ...
        @property
        def parent(self, /) -> str: ...
        @property
        def tool(self, /) -> str |None: ...
    @final
    class Downloaded(Origin):
        __match_args__: Final = ("url", "name")
        def __new__(cls, /, url: str, name: str |None) -> Origin.Downloaded: ...
        @property
        def name(self, /) -> str |None: ...
        @property
        def url(self, /) -> str: ...
    @final
    class Incident(Origin):
        __match_args__: Final = ("incident", "cover_term", "mission_team", "network", "machine", "location")
        def __new__(cls, /, incident: str, cover_term: str |None, mission_team: str |None, network: str |None, machine: str |None, location: str |None) -> Origin.Incident: ...
        @property
        def cover_term(self, /) -> str |None: ...
        @property
        def incident(self, /) -> str: ...
        @property
        def location(self, /) -> str |None: ...
        @property
        def machine(self, /) -> str |None: ...
        @property
        def mission_team(self, /) -> str |None: ...
        @property
        def network(self, /) -> str |None: ...
    @final
    class MemoryDump(Origin):
        __match_args__: Final = ("parent", "dangling", "reconstructed", "base_addr")
        def __new__(cls, /, parent: str, dangling: bool, reconstructed: Sequence[str], base_addr: str |None) -> Origin.MemoryDump: ...
        @property
        def base_addr(self, /) -> str |None: ...
        @property
        def dangling(self, /) -> bool: ...
        @property
        def parent(self, /) -> str: ...
        @property
        def reconstructed(self, /) -> list[str]: ...
    @final
    class None_(Origin):
        __match_args__: Final = ()
        def __getitem__(self, /, key: int) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> Origin.None_: ...
    @final
    class Source(Origin):
        __match_args__: Final = ("repo", "commitish", "commit", "flags", "system", "supporting")
        def __new__(cls, /, repo: str, commitish: str |None, commit: str, flags: Sequence[str], system: str, supporting: bool) -> Origin.Source: ...
        @property
        def commit(self, /) -> str: ...
        @property
        def commitish(self, /) -> str |None: ...
        @property
        def flags(self, /) -> list[str]: ...
        @property
        def repo(self, /) -> str: ...
        @property
        def supporting(self, /) -> bool: ...
        @property
        def system(self, /) -> str: ...
    @final
    class Transformed(Origin):
        __match_args__: Final = ("tool", "parent", "dangling", "flags", "cmd")
        def __new__(cls, /, tool: str |None, parent: str, dangling: bool, flags: Sequence[str], cmd: str |None) -> Origin.Transformed: ...
        @property
        def cmd(self, /) -> str |None: ...
        @property
        def dangling(self, /) -> bool: ...
        @property
        def flags(self, /) -> list[str]: ...
        @property
        def parent(self, /) -> str: ...
        @property
        def tool(self, /) -> str |None: ...
    @final
    class Unpacked(Origin):
        __match_args__: Final = ("tool", "parent", "dangling")
        def __new__(cls, /, tool: str |None, parent: str, dangling: bool) -> Origin.Unpacked: ...
        @property
        def dangling(self, /) -> bool: ...
        @property
        def parent(self, /) -> str: ...
        @property
        def tool(self, /) -> str |None: ...
    @final
    class Wire(Origin):
        __match_args__: Final = ("sniffer", "source", "destination")
        def __new__(cls, /, sniffer: str, source: str |None, destination: str |None) -> Origin.Wire: ...
        @property
        def destination(self, /) -> str |None: ...
        @property
        def sniffer(self, /) -> str: ...
        @property
        def source(self, /) -> str |None: ...

@final
class Reaction:
    @property
    def args(self, /) -> dict[str, GenericJobArgs]: ...
    @property
    def completed_sub_reactions(self, /) -> int: ...
    @property
    def creator(self, /) -> str: ...
    @property
    def current_stage(self, /) -> int: ...
    @property
    def current_stage_length(self, /) -> int: ...
    @property
    def current_stage_progress(self, /) -> int: ...
    @property
    def ephemeral(self, /) -> list[str]: ...
    @property
    def generators(self, /) -> list[Incomplete]: ...
    @property
    def group(self, /) -> str: ...
    @property
    def has_cache(self, /) -> bool: ...
    @property
    def id(self, /) -> Incomplete: ...
    @property
    def jobs(self, /) -> list[Incomplete]: ...
    @property
    def parent(self, /) -> Incomplete |None: ...
    @property
    def parent_ephemeral(self, /) -> dict[str, Incomplete]: ...
    @property
    def pipeline(self, /) -> str: ...
    @property
    def repos(self, /) -> list[RepoDependency]: ...
    @property
    def samples(self, /) -> list[str]: ...
    @property
    def sla(self, /) -> datetime: ...
    @property
    def status(self, /) -> ReactionStatus: ...
    @property
    def sub_reactions(self, /) -> int: ...
    @property
    def tags(self, /) -> list[str]: ...
    @property
    def trigger_depth(self, /) -> int |None: ...

@final
class ReactionCache:
    def __new__(cls, /, generic: dict[str, str] = ..., files: Sequence[str] = ...) -> ReactionCache: ...

@final
class ReactionCreation:
    @property
    def id(self, /) -> Incomplete: ...

@final
class ReactionRequest:
    def __new__(cls, /, group: str, pipeline: str, args: dict[str, GenericJobArgs] = ..., sla: int |None = None, tags: Sequence[str] = ..., parent: "UUID | None" = None, samples: Sequence[str] = ..., buffers: dict[str, str] = ..., repos: Sequence[RepoDependencyRequest] = ..., trigger_depth: int |None = None, cache: ReactionCache = ...) -> ReactionRequest: ...

@final
class ReactionStatus:
    Completed: Final[ReactionStatus]
    Created: Final[ReactionStatus]
    Failed: Final[ReactionStatus]
    Started: Final[ReactionStatus]
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class ReactionsBlocking:
    def create(self, /, data: ReactionRequest) -> ReactionCreation: ...
    def create_bulk(self, /, reqs: Sequence[ReactionRequest]) -> BulkReactionResponse: ...
    def get(self, /, group: str, id: Incomplete) -> Reaction: ...

@final
class RepoDependency:
    @property
    def commitish(self, /) -> str |None: ...
    @commitish.setter
    def commitish(self, /, value: str |None) -> None: ...
    @property
    def kind(self, /) -> CommitishKinds |None: ...
    @kind.setter
    def kind(self, /, value: CommitishKinds |None) -> None: ...
    @property
    def url(self, /) -> str: ...
    @url.setter
    def url(self, /, value: str) -> None: ...

@final
class RepoDependencyRequest:
    def __new__(cls, /, url: str, commitish: str |None = None, kind: CommitishKinds |None = None) -> RepoDependencyRequest: ...

@final
class Sample:
    @property
    def comments(self, /) -> list[Comment]: ...
    @property
    def md5(self, /) -> str: ...
    @property
    def sha1(self, /) -> str: ...
    @property
    def sha256(self, /) -> str: ...
    @property
    def submissions(self, /) -> list[SubmissionChunk]: ...
    @property
    def tags(self, /) -> dict[str, dict[str, set[str]]]: ...

@final
class SampleCursor:
    def data(self, /) -> list[Sample]: ...
    def exhausted(self, /) -> bool: ...
    def refill(self, /) -> None: ...

@final
class SampleListLine:
    @property
    def groups(self, /) -> set[str]: ...
    @property
    def sha256(self, /) -> str: ...
    @property
    def submission(self, /) -> Incomplete |None: ...
    @property
    def uploaded(self, /) -> datetime: ...

@final
class SampleListLineCursor:
    def data(self, /) -> list[SampleListLine]: ...
    def exhausted(self, /) -> bool: ...
    def refill(self, /) -> None: ...

@final
class SubmissionChunk:
    @property
    def description(self, /) -> str |None: ...
    @property
    def groups(self, /) -> list[str]: ...
    @property
    def id(self, /) -> Incomplete: ...
    @property
    def name(self, /) -> str |None: ...
    @property
    def origin(self, /) -> Origin: ...
    @property
    def submitter(self, /) -> str: ...
    @property
    def uploaded(self, /) -> datetime: ...

@final
class TagCounts:
    @property
    def cursor(self, /) -> Incomplete |None: ...
    @property
    def tags(self, /) -> dict[str, TagKeyCounts]: ...
    @property
    def total(self, /) -> int: ...

@final
class TagCountsCursor:
    def data(self, /) -> dict[str, TagKeyCounts]: ...
    def exhausted(self, /) -> bool: ...
    def refill(self, /) -> None: ...

@final
class TagKeyCounts:
    @property
    def total(self, /) -> int: ...
    @property
    def values(self, /) -> dict[str, int]: ...

@final
class ThoriumBlocking:
    def __new__(cls, /, host: str, token: str |None = None, username: str |None = None, password: str |None = None, settings: ClientSettings = ...) -> ThoriumBlocking: ...
    @property
    def basic(self, /) -> BasicBlocking: ...
    @property
    def files(self, /) -> FilesBlocking: ...
    @classmethod
    def from_ctl_conf_file(cls, /, path: str) -> ThoriumBlocking: ...
    @classmethod
    def from_key_file(cls, /, path: str) -> ThoriumBlocking: ...
    @property
    def jobs(self, /) -> JobsBlocking: ...
    @property
    def reactions(self, /) -> ReactionsBlocking: ...


from uuid import UUID
